### ISSUE TITLE
update pre-commit

### ISSUE THREAD

**Issue by kjappelbaum** [aiidalab/aiidalab-eln#71]
@kjappelbaum looks like the tests are failing due to this pre-commit update.

_Originally posted by @danielhollas in https://github.com/aiidalab/aiidalab-eln/issues/70#issuecomment-1329713555_

**Comment by kjappelbaum** [comment]
comments in the flake8 section need to change for major version 6

**Comment by yakutovicha** [comment]
I believe this can be closed?

**Comment by kjappelbaum** [comment]
yes, forgot to link the issue

**Comment by kjappelbaum** [comment]
closed via #72
