### ISSUE TITLE
Deprecation of dependencies format

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-eln#82]
In QeApp, the follow deprecation is raised when install the package:

"""
DEPRECATION: aiidalab-eln 0.1.2 has a non-standard dependency specifier aiida-core<3",>=1.1.0. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of aiidalab-eln or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
""

**Comment by danielhollas** [comment]
pip 24.1 started enforcing this, so aiidalab-eln==0.1.2 is no longer installable. 

This was fixed in #85 and released in 0.1.3

**Comment by danielhollas** [comment]
I apparently don't have permissions on this repo so cannot close this issue myself.

**Comment by unkcpz** [comment]
I close it. Thanks @danielhollas !
